title: gRPC Errors
email: hi@avi.im
description: A handy guide to gRPC errors
owner_nick: v
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
owner_url: "http://avi.im"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
